[package]
name = "stat"
version = "0.0.1"
authors = []
build = "../#common/mkmain.rs"

[lib]
name = "uu_stat"
path = "stat.rs"

[dependencies]
getopts = "0.2.18"
time = "0.1.40"

[dependencies.uucore]
version = "0.0.1"
features = ["entries"]

[[bin]]
name = "stat"
path = "../#common/uumain.rs"
